FEATURE_FLAGS = {
    'assistantsEnabled': True,
    'promptOptimizer': True,
    'ragEnabled': True,
    'sourcesEnabled': True,
    'uploadDocuments': True,
    'assistantCreator': True,
    'assistants': True,
    'overrideUneditablePrompts': False,
    'overrideInvisiblePrompts': False,
    'extractDocumentsLocally': False,
    'enableMarket': False,
    'promptPrefixCreate': False,
    'outputTransformerCreate': False,
    'workflowRun': True,
    'workflowCreate': False,
    'rootPromptCreate': True,
    'pluginsOnInput': True, # if all plugin features are disables, then this should be disabled. ex. ragEnabled, codeInterpreterEnabled etc.
    'dataSourceSelectorOnInput': True,
    'followUpCreate': True,
    'marketItemDelete': False,
    'automation': True,
    'codeInterpreterEnabled': False,
    'dataDisclosure': False,
    'storeCloudConversations': False,
    'qiSummary': False,
    'apiKeys': True,
    'assistantAdminInterface': False,
    'createAstAdminGroups': False,
    # 'adminInterface': False, Is dynamically added in get_user_feature_flags
    'artifacts': True,
    'mtdCost': False,
    'highlighter': True,
    'assistantApis': False,
    'mixPanel': False,
    'integrations': False
  }