scopes = {
    "google": {
        "google_calendar": ["https://www.googleapis.com/auth/calendar"],
        "google_sheets": ["https://www.googleapis.com/auth/spreadsheets"],
        "google_docs": ["https://www.googleapis.com/auth/documents"],
        "google_drive": ["https://www.googleapis.com/auth/drive"],
        "google_forms": [
            "https://www.googleapis.com/auth/forms.responses.readonly",
            "https://www.googleapis.com/auth/forms.body",
        ],
        "google_gmail": [
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/directory.readonly",
            "https://www.googleapis.com/auth/profile.emails.read",
            "openid",
        ],
        "google_contacts": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/directory.readonly",
            "https://www.googleapis.com/auth/profile.emails.read",
            "openid",
        ],
    },
    "microsoft": {
        "microsoft_calendar": [
            "Calendars.Read",
            "Calendars.ReadWrite",
            "Calendars.Read.Shared",
        ],
        "microsoft_drive": ["Files.Read", "Files.ReadWrite"],
        "microsoft_excel": ["Files.Read", "Files.ReadWrite"],
        "microsoft_onenote": ["Notes.Read", "Notes.ReadWrite"],
        "microsoft_outlook": ["Mail.Read", "Mail.ReadWrite", "Mail.Send"],
        "microsoft_planner": ["Group.Read.All", "Group.ReadWrite.All"],
        "microsoft_sharepoint": ["Sites.Read.All", "Sites.ReadWrite.All"],
        "microsoft_teams": [
            "Team.ReadBasic.All",
            "ChannelMessage.Send",
            "Chat.ReadWrite",
            "ChannelSettings.Read.All",
            "Channel.ReadBasic.All",
            "ChannelSettings.ReadWrite.All",
            "Group.Read.All",
            "Directory.Read.All",
            "Group.ReadWrite.All",
            "Directory.ReadWrite.All",
            "OnlineMeetings.ReadWrite",
        ],
        "microsoft_contacts": ["Contacts.Read", "Contacts.ReadWrite"],
        "microsoft_user_groups": [
            "Group.Read.All",
            "Group.ReadWrite.All",
            "Directory.Read.All",
            "Directory.ReadWrite.All",
        ],
        "microsoft_word": [
            "Files.Read",
            "Files.ReadWrite",
            "Sites.Read.All",
            "Sites.ReadWrite.All",
        ],
    },
}
